### ISSUE TITLE
Feature request: Better handling of locked templates

### ISSUE THREAD

**Issue by andreasbaekdahl** [CiscoDevNet/terraform-provider-sdwan#107] opened 2023-11-22 20:53 UTC
Templates may end up in locked state after making changes, resulting in the following error.

```
│ Warning: Client Warning
│ 
│   with sdwan_cisco_vpn_interface_feature_template.TEST,
│   on feature_templates.tf line 180, in resource "sdwan_cisco_vpn_interface_feature_template" "TEST":
│  180: resource "sdwan_cisco_vpn_interface_feature_template" "TEST" {
│ 
│ Failed to modify template due to template being locked by another change. Template changes will not be applied. Re-run 'terraform apply' to try
│ again.
```

Would it be possible to implement one (or both) of these:
 - Ensure the template is always left in unlocked when making changes
 - Wait for template to unlock instead of throwing the Warning

Maybe there is some other solution? I know this issue can also appear when working with SD-WAN through the GUI.

**Comment by danischm** [comment] 2023-11-22 21:29
> Ensure the template is always left in unlocked when making changes

This is something vManage does inherently and is not something we can control via API.

> Wait for template to unlock instead of throwing the Warning

The template is locked indefinitely until deployed.

The problem is to some extend described here: https://registry.terraform.io/providers/CiscoDevNet/sdwan/latest/docs/guides/updating_templates . vManage locks all the associated deployed templates once a change to single (already deployed) template is being made. The lock is only released after the change has been deployed (`sdwan_attach_feature_template` resource). In the GUI you are kinda forced to re-deploy changes immediately after making changes to an already deployed template.

**Comment by danischm** [comment] 2023-11-28 06:43
I will close this for now as I don't see a better way to handle to this. This will likely improve with config groups and feature profiles.

**Closed by danischm** 2023-11-28 06:43 UTC
